### ISSUE TITLE
Problems with the loadavg in windows

### ISSUE THREAD

**Issue by Alpha018** [lfortin/node-os-monitor#1]
Hello some time ago I decided to occupy this module and testing the monitor I could notice that in windows 10 the attribute loadavg had an array list of values in 0 without showing this data, this is due to the same operating system or is due to another factor?

**Comment by lfortin** [comment]
Thank you for opening this issue.

As specified in Node.js docs:
The load average is a UNIX-specific concept with no real equivalent on Windows platforms. On Windows, the return value is always [0, 0, 0].

Ref.: https://nodejs.org/dist/latest/docs/api/os.html#os_os_loadavg
