### ISSUE TITLE
[Feature Request] How about adding support for Disk Usage

### ISSUE THREAD

**Issue by i-break-codes** [lfortin/node-os-monitor#2]
I was thinking it would be great if you add support for monitoring disk usage. If it hits < N GB, it will raise alerts.

**Comment by lfortin** [comment]
Thanks @i-break-codes for opening this feature request.

The module os-monitor was originally meant to be used along with the [os](https://nodejs.org/dist/latest/docs/api/os.html) core module in Node.js . However, I will keep this issue opened for future reference. I may consider adding free disk space checking in the future.

Meanwhile, here are a few modules you may use to monitor free disk space:

https://www.npmjs.com/package/node-df
https://www.npmjs.com/package/check-disk-space

**Comment by lfortin** [comment]
@i-break-codes 

I found a related pending PR in the Node.js project:
https://github.com/nodejs/node/pull/31351

If it is merged into Node.js core, I will consider adding support for disk usage monitoring into os-monitor.

**Comment by i-break-codes** [comment]
Hey, thanks for the update. Am already using another tools but I thought to suggest you this as it will help you complete your package in a way as it's relevant.

Also, glad to hear that you will consider adding the support going forward. Looking forward to it 🙂

**Comment by lfortin** [comment]
Support for disk usage added.
